@extends('public.layout')
@section('content')
@if ($hero)
<section class="hero"><div class="container hero-grid"><article class="hero-main">
    <img src="{{ $hero->display_image }}" alt="{{ $hero->headline }}" onerror="this.onerror=null;this.src='{{ asset('images/placeholder.svg') }}';">
    <div class="hero-copy"><div class="eyebrow"><span>{{ $hero->category?->name ?? 'Featured' }}</span>@if($hero->location)<span>{{ $hero->location }}</span>@endif</div><h1>{{ $hero->headline }}</h1><p>{{ Str::limit(strip_tags($hero->short_description ?: $hero->content), 180) }}</p><a class="submit-button" href="{{ route('news.show', $hero->slug) }}">Read More →</a></div>
</article><aside class="hero-side"><h2>Latest News</h2>@foreach ($latest->take(4) as $item)<a class="side-news" href="{{ route('news.show', $item->slug) }}"><span class="side-thumb"><img src="{{ $item->display_image }}" alt="{{ $item->headline }}" onerror="this.onerror=null;this.src='{{ asset('images/placeholder.svg') }}';"></span><span><time>{{ $item->published_at?->diffForHumans() }}</time><h3>{{ $item->headline }}</h3></span></a>@endforeach</aside></div></section>
@else
<section class="page-hero"><div class="container"><p class="section-kicker">JANKATHA / NEWSROOM</p><h1>Real stories are coming soon.</h1><p>Jankatha is ready for the stories of your city, district and community.</p></div></section>
@endif
<section class="content-section"><div class="container"><x-public.section-heading title="Top Categories" :link="route('news.index')" link-text="All news"/><div class="category-grid">@foreach($categories as $category)<a class="category-tile" href="{{ route('category.show', $category->slug) }}">{{ $category->name }}</a>@endforeach</div></div></section>
<section class="content-section"><div class="container split-section"><div><x-public.section-heading title="Local News" :link="route('local-news')"/><div class="local-list">@forelse($localNews as $item)<a class="local-item" href="{{ route('news.show', $item->slug) }}"><span class="side-thumb"><img src="{{ $item->display_image }}" alt="{{ $item->headline }}" onerror="this.onerror=null;this.src='{{ asset('images/placeholder.svg') }}';"></span><span><div class="eyebrow"><span>{{ $item->category?->name }}</span></div><h3>{{ $item->headline }}</h3><p>{{ collect([$item->location,$item->district,$item->state])->filter()->join(' · ') }}</p></span></a>@empty<p class="empty-state">Local stories will appear here as they are published.</p>@endforelse</div></div><div><x-public.section-heading title="Breaking" :link="route('breaking-news')"/><div class="sidebar">@forelse($breakingNews as $item)<a class="side-news" href="{{ route('news.show', $item->slug) }}"><span class="side-thumb"><img src="{{ $item->display_image }}" alt="{{ $item->headline }}" onerror="this.onerror=null;this.src='{{ asset('images/placeholder.svg') }}';"></span><span><time>{{ $item->published_at?->diffForHumans() }}</time><h3>{{ $item->headline }}</h3></span></a>@empty<p>No breaking news right now.</p>@endforelse</div></div></div></section>
<section class="content-section"><div class="container"><x-public.section-heading title="Video News" :link="route('video-news')"/><div class="video-strip">@forelse($videoNews as $item)<a class="video-card" href="{{ route('news.show', $item->slug) }}"><img src="{{ $item->display_image }}" alt="{{ $item->headline }}" onerror="this.onerror=null;this.src='{{ asset('images/placeholder.svg') }}';"><h3>{{ $item->headline }}</h3></a>@empty<p class="empty-state">Video reports will appear here soon.</p>@endforelse</div></div></section>
<section class="content-section"><div class="container"><x-public.section-heading title="Photo News" :link="route('photo-news')"/><div class="news-grid">@forelse($photoNews as $item)<x-public.news-card :news="$item" />@empty<p class="empty-state">Photo stories will appear here soon.</p>@endforelse</div></div></section>
<section class="content-section"><div class="container"><div class="cta"><div><p class="section-kicker">CITIZEN JOURNALISM</p><h2>आपकी खबर, आपकी आवाज़</h2><p>अपने शहर, गांव और क्षेत्र की खबर Jankatha तक पहुँचाएँ।</p></div><a class="submit-button" href="{{ route('submit-news') }}">अपनी खबर भेजें</a></div></div></section>
<section class="content-section"><div class="container"><div class="newsletter"><div><p class="section-kicker">STAY INFORMED</p><h2>Get the important updates.</h2><p>Newsletter subscriptions will be available soon.</p></div><form onsubmit="return false"><input type="email" placeholder="Your email address" aria-label="Your email address"><button type="submit">Notify me</button></form></div></div></section>
@endsection
